---
tap_install:
  values:
    profile: full
    excluded_packages:
      - eventing.tanzu.vmware.com
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    shared:
      ingress_domain: sysco.tap-pilot.com
      ingress_issuer: ""
      image_registry:
        project_path: "gcr.io/fe-cpage/tap"

    buildservice:
      kp_default_repository: "gcr.io/fe-cpage/build"

    supply_chain: testing_scanning

    ootb_supply_chain_testing_scanning:
      registry:
        server: "gcr.io/fe-cpage"
        repository: "tap/supply-chain"
      gitops:
        ssh_secret: git-https
        username: cpage-pivotal
        branch: main
        commit_message: "Update from TAP Supply Chain Choreographer"
        email: pcorby@vmware.com
        server_address: https://github.com/
        repository_owner: cpage-pivotal
        repository_name: tap-gitops

    contour:
      envoy:
        service:
          type: LoadBalancer # NodePort can be used if your Kubernetes cluster doesn't support LoadBalancing.

    appliveview:
      ingressEnabled: true
      tls:
        namespace: contour-tls
        secretName: tls

    appliveview_connector:
      backend:
        ingressEnabled: true
        host: appliveview.sysco.tap-pilot.com

    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/sysco-pilot/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/tanzu-end-to-end/tap-gitops-workshop
      additional_sources:
        - git:
            ref: origin/main
            subPath: clusters/sysco-pilot/cluster-config/namespace-provisioner/namespace-resources
            url: https://github.com/tanzu-end-to-end/tap-gitops-workshop
          path: _ytt_lib/namespace-resources
      overlay_secrets:
        - name: workload-git-auth-overlay
          namespace: tap-install
          create_export: true

    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      ingressEnabled: "true"
      tls:
        namespace: contour-tls
        secretName: tls
      app_config:
        app:
          baseUrl: https://tap-gui.sysco.tap-pilot.com
        catalog:
          locations:
            - type: url
              target: https://github.com/cpage-pivotal/spring-sensors/blob/main/catalog/catalog-info.yaml
        backend:
          baseUrl: https://tap-gui.sysco.tap-pilot.com
          cors:
            origin: https://tap-gui.sysco.tap-pilot.com

    metadata_store:
      app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
      ns_for_export_app_cert: "*"

    scanning:
      metadataStore:
        url: "" # Disable embedded integration since it's deprecated

    grype:
      namespace: "default" # (optional) Defaults to default namespace.
      targetImagePullSecret: "registry-credentials"
