---
apiVersion: v1
kind: Secret
metadata:
  name: git-https
  namespace: tap-install
type: kubernetes.io/basic-auth
stringData:
  username: # Username for your Github account
  password: # Github developer token
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # Insert your base64-encoded credentials here
