secrets:
    sops:
        age_key: ENC[AES256_GCM,data:HzJFcqIeqlRyXQ7aVKqeDhUSsoXENv2Q7jr3utbKot0DCqUxrE4o3C9hY+kTY4efIX0iSulF8/fr1lBAuRBjJbswD3cdMOR5ZK1k,iv:OZY79+Ys/q0D+SVQWiwJTbrco3R7b3Tq7KWEQ1yHZ+I=,tag:UnYaR2Puxkm82VUVr9YwJQ==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:MLZJcBc5onSBdh1t3baG4LUvmpZg921WFg==,iv:DbnhEKNgvdAcPWLedzNHXXTHtM3K1h9pSTyT5cOgCEY=,tag:fuNVKlbeKyUU+Mev4Ywqww==,type:str]
            username: ENC[AES256_GCM,data:+DF1ekiew1967iO/87Ytc8k=,iv:1+JAVMKMXT0g4MTXJeWyUppSjs8qyfYZ2loIT6UZvjc=,tag:qJEFYj0aqE6SH0gPy2cBjA==,type:str]
            password: ENC[AES256_GCM,data:aVflay0vv+A=,iv:zkdj4vawZ7UfBTTv2mp+XCxKpDUPQc+/fspbxAbgERo=,tag:QdotPRGU26V7EkS5hSSVNw==,type:str]
        git:
            #ENC[AES256_GCM,data:RbjR2uWwfwXQKhcu19YVekuYzZcXX4LSwivNJ9G2MnN0II7eXPinDdIwzjX7ew==,iv:4OUfYP1XdKSJTZ6tH4/hzz53FzknNWn3id7mrubyi2g=,tag:cfhps9D6qxZC3dGRdQ5l0Q==,type:comment]
            basic_auth:
                username: ENC[AES256_GCM,data:cHwYlFG4JK5L9s9z4w==,iv:oYmldGqaUF2usNwYafKjkYSbajMx50VQQm1baNFHXus=,tag:C9UA0czjMwvdx81uRBSEnA==,type:str]
                password: ENC[AES256_GCM,data:XIdVwQy1lUWhKNL3WlrCIKq4rU+KCwuHx1RRvqdLYQl5o6OweINdRw==,iv:vO5uyr6n1GCkvzlhIyTwT/I2onNbCs9kPxVwSUtJ9Wg=,tag:DdmZcnXh9K4QFSHJXuISLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nm6xftel9un7gu9d4mm0mzzq5aylv9jny0ctpkv8cfygc3ev0fnqztswcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL2w4c0UxQlEwTjdYa1RM
            T1VOaXZRREp1UHhDY1JsanpIMXo3a2ZWQ0dZClliblRkSEVDZk0rM0VOejZYck9F
            blQ2ME01ZUVwS2MxTlV5VEJSR3lsYVEKLS0tIHBESGNpUTFOMXA3dGtoN1lsUlc1
            MHBoajFycWNvbitJUDZiZ0NTeTRvelEKoJsRZNiU6s1Ff2JVXpTf1CCSSari+YGG
            YUmONtPlDVyAgxzbyqG+J6d2y9J9tnG088FykjYr+4psz53FMrPk4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T16:47:46Z"
    mac: ENC[AES256_GCM,data:3xVYEAo6TwteUzndflf8FFNtbiOzmXrnrOJ4QoYVBRFyMKnzubcn/E7Fg8YFOP96Mz/uSjKPFzsePllzXzvrh9epgnmYnsGYo7ncSm9wEJuSf//iC1U54D1/u1oBGnak4jcDZXqh3QLT9G4HnUXaPxPRdQ8nTshdHEB+dfQdpSw=,iv:FcxVgSMGhRM7MrAAXSi0seRZ3XFTthhEwuJbMA1kmXA=,tag:zMniVyMdljzwqQR+HGHl3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
