#cloud-config

package_update: true
package_upgrade: true

users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_authorized_keys:
      - ${ssh_public_key}

write_files:
  - encoding: b64
    owner: ${username}:${username}
    content: ${kubeconfig}
    path: /home/${username}/.kube/config
    defer: true
  - encoding: b64
    content: ${install_tools_script}
    path: /usr/local/bin/tap-gitops-workshop-scripts/install-tools.sh
    permissions: "0755"
  - encoding: b64
    content: ${install_tanzu_script}
    path: /usr/local/bin/tap-gitops-workshop-scripts/install-tanzu.sh
    permissions: "0755"
  - encoding: b64
    content: ${login_gh_script}
    path: /usr/local/bin/tap-gitops-workshop-scripts/login-gh.sh
    permissions: "0755"
  - encoding: b64
    content: ${tap_version}
    path: /usr/local/bin/tap-gitops-workshop-scripts/tap-version.yaml
    permissions: "0755"

runcmd:
  - |
    su - ${username} << EOM
      /usr/local/bin/tap-gitops-workshop-scripts/install-tools.sh
    EOM
  - |
    su - ${username} << EOM
      export GH_USERNAME="${gh_username}"
      export GH_TOKEN="${gh_token}"

      export TANZU_NETWORK_REFRESH_TOKEN="${tanzu_network_refresh_token}"
      export TANZU_REGISTRY_USERNAME="${tanzu_registry_username}"
      export TANZU_REGISTRY_PASSWORD="${tanzu_registry_password}"

      /usr/local/bin/tap-gitops-workshop-scripts/install-tanzu.sh
      /usr/local/bin/tap-gitops-workshop-scripts/login-gh.sh
    EOM
  - |
    su - ${username} << EOM
      # NOTE: left aligned exports on purpose because of the heredoc
      cat <<EOF > ~/.envrc
    export GH_USERNAME="${gh_username}"
    export GH_TOKEN="${gh_token}"

    export TANZU_NETWORK_REFRESH_TOKEN="${tanzu_network_refresh_token}"
    export TANZU_REGISTRY_USERNAME="${tanzu_registry_username}"
    export TANZU_REGISTRY_PASSWORD="${tanzu_registry_password}"
    EOF

      direnv allow
    EOM
