---
tap_install:
  values:
    profile: full

    shared:
      ingress_domain: # Wildcard DNS Domain (e.g. tap.myexample.com)
      image_registry:
        project_path: # Image registry project path (e.g. harbor.myexample.com/tap/tap-images)
        username: # Registry username

      kubernetes_version: # Kubernetes version (e.g. 1.25.9)

    ceip_policy_disclosed: true

    # These packages will be deprecated in future versions of TAP, so we will exclude them to free up space on the cluster
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - eventing.tanzu.vmware.com
